name       : plasma-vault
version    : 5.23.5
release    : 48
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/plasma-vault-5.23.5.tar.xz : 0d6cffa89f53de921a983340b066119315c8bbff613ddc9bdedbe2247018c5bd
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
