name       : plasma-vault
version    : 5.21.5
release    : 38
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/plasma-vault-5.21.5.tar.xz : 7519b5da20e59f571128b66fc22e5d2b2027752e01caa1c70574b12dcfd8979b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
