name       : plasma-vault
version    : 5.23.4
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.4/plasma-vault-5.23.4.tar.xz : c627e8872b2f3847c77451c07f64ebfa3774574f37871af879b8acb7e6e9c9ab
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
