name       : plasma-vault
version    : 5.23.3
release    : 46
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.3/plasma-vault-5.23.3.tar.xz : a27a13fe0a2d316045e1063215e301b192defe5a93b04baaaa4a855f01c03f18
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
