name       : plasma-vault
version    : 5.17.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.3/plasma-vault-5.17.3.tar.xz : fcb5fb7f31653aafe0f7d5fe56947cd20b6bfea3a85e973dceeaf93c83459d8d
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kactivities-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
    %qml_cache
