name       : plasma-vault
version    : 5.14.5
release    : 2
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.5/plasma-vault-5.14.5.tar.xz : 23d6626918b4b0114e928b2bbb5f2a55a0dd919e270d27a7138cb3598125249f
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kactivities-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
    %qml_cache
