name       : plasma-vault
version    : 5.25.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/plasma-vault-5.25.3.tar.xz : 06105ca3329f50b99e56d13b3b077657857afb90be17e781054cd4fd7c3e0bde
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
